site_name: GuimoNotion
site_author: Guillermo Balsera Suárez
site_description: Apuntes en español sobre distintas tecnologías de desarrrollo, desde lenguajes de programación hasta frameworks de frontend y backend.
copyright: Copyright &copy; 2024 - Guillermo Balsera

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - tags
  - search

theme:
  name: material
  language: es
  logo: assets/guimonotion.svg
  favicon: assets/guimonotion.svg
  features:
    - content.code.copy
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
  font:
    text: Rubik
    code: Roboto Mono
  palette:
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/brightness-2
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo claro

extra_css:
  - stylesheets/style.css

nav:
  - Inicio: index.md
  - Lenguajes:
      - Bash Script: languages/bashScript/index.md
      - Kotlin: languages/kotlin/index.md
      - Python:
          - Introducción: languages/python/index.md
          - Variables:
              - Listas o Arrays: languages/python/variables/array/index.md
              - Tuplas o Tuples: languages/python/variables/tuple/index.md
              - Diccionarios o Dictionaries: languages/python/variables/dictionary/index.md
              - Conjuntos o Sets: languages/python/variables/set/index.md
          - Estructuras de control: languages/python/control_structures/index.md
          - Funciones: languages/python/functions/index.md
          - Objectos: languages/python/objects/index.md
          - Ficheros:
              - Manejo de directorios: languages/python/files_directories/index.md
              - Lectura de ficheros: languages/python/files_directories/file_read/index.md
              - Escritura de ficheros: languages/python/files_directories/file_write/index.md
          - Bases de datos:
              - SQLite: languages/python/databases/sqlite/index.md
              - PostgreSQL: languages/python/databases/postgresql/index.md
              - MySQL: languages/python/databases/mysql/index.md
              - MongoDB: languages/python/databases/mongodb/index.md
      - Java:
          - Introducción: languages/java/index.md
          - Estructuras de control: languages/java/control_structures/index.md
  - Frontend:
      - Angular:
          - Introducción: frameworks/frontend/angular/index.md
          - Instalación: frameworks/frontend/angular/installation/index.md
          - Estructura del proyecto: frameworks/frontend/angular/project_hierarchy/index.md
          - Componentes: frameworks/frontend/angular/components/index.md
          - Databinding: frameworks/frontend/angular/databinding/index.md
          - Input y Output: frameworks/frontend/angular/input_output/index.md
          - Proyección de contenido: frameworks/frontend/angular/projection/index.md
          - Ciclos de vida: frameworks/frontend/angular/life_cicle/index.md
          - Rutas: frameworks/frontend/angular/routes/index.md
          - Recursos adicionales: frameworks/frontend/angular/additional_resources/index.md
#      - Electron: frameworks/frontend/electron/index.md
#      - Ionic: frameworks/frontend/ionic/index.md
#      - React: frameworks/frontend/react/index.md
      - MkDocs: frameworks/frontend/mkdocs/index.md
  - BackEnd:
      - PHP-Laravel:
          - Introducción: frameworks/backend/php-laravel/index.md
          - Modelo: frameworks/backend/php-laravel/model/index.md
          - Seeders: frameworks/backend/php-laravel/seeders/index.md
          - Factories: frameworks/backend/php-laravel/factories/index.md
          - Migraciones: frameworks/backend/php-laravel/migrations/index.md
          - Resources: frameworks/backend/php-laravel/resources/index.md
          - Collections: frameworks/backend/php-laravel/collections/index.md
          - Controllers: frameworks/backend/php-laravel/controllersView/index.md
          - Controllers API REST: frameworks/backend/php-laravel/controllersAPI/index.md
#      - Spring-Boot: frameworks/backend/spring-boot/index.md
  - Otros:
      - Markdown: others/markdown/index.md
      - Node: others/node/index.md
      - JSON: others/json/index.md
      - XML: others/xml/index.md
      - YAML: others/yaml/index.md
